name = "TransferEntropy"
uuid = "ea221983-52f3-5440-99c7-13ea201cd633"
repo = "https://github.com/kahaaga/TransferEntropy.jl.git"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
PerronFrobenius = "260eed61-d0e8-5f1e-b040-a9756a401c97"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Simplices = "d5428e67-3037-59ba-9ab1-57a04f0a3b6a"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StateSpaceReconstruction = "1441a9f6-6a74-5418-a591-cdf1d78a07f0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
